---
- name: RedHat | add OpenIO SDS repository
  include_role:
    name: ansible-role-repo-openio-sds
  when: netdata_manage_repository

- name: RedHat |Install packages
  package:
    name: "{{ pkg }}"
    state: present
  with_items: "{{ netdata_packages }}"
  loop_control:
    loop_var: pkg
...
